apps/lms/urls.py
from django.urls import path

from apps.lms.views import StudentListView, StudentCreateView, StudentUpdateView

app_name = 'lms'


urlpatterns = [
    path('', StudentListView.as_view(), name='student-list'),
    path('student', StudentCreateView.as_view(), name='student-create'),
    path('student/<str:pk>/', StudentUpdateView.as_view(), name='student-update')
]

config/urls.py
from django.contrib import admin
# from django.http import HttpResponse
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns


# def my_view(request):
#     return HttpResponse('OK')


urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('apps.imdb.urls', namespace='imdb')),
    path('lms/', include('apps.lms.urls', namespace='lms')),
    path('admin/', admin.site.urls),
    path('auth/', include('apps.authentication.urls', namespace='auth')),

]

apps/lms/models.py
from django.db import models

# Create your models here.

from django.utils.translation import gettext_lazy as _


class Student(models.Model):
    name = models.CharField(_('Name'), max_length=255)
    birth_date = models.DateField(_('Birth Date'))


class Teacher(models.Model):
    name = models.CharField(_('Name'), max_length=255)
    birth_date = models.DateField()


class Group(models.Model):
    name = models.CharField(max_length=255)
    teacher = models.ForeignKey(Teacher, related_name='groups', on_delete=models.PROTECT)
    students = models.ManyToManyField(Student, related_name='groups')

apps/lms/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, CreateView, UpdateView
from django.urls import reverse_lazy
from bootstrap_datepicker_plus.widgets import DatePickerInput
from .models import Student


class StudentListView(LoginRequiredMixin, ListView):
    model = Student


class StudentCreateView(CreateView):
    model = Student
    success_url = reverse_lazy('lms:student-list')
    fields = ['name', 'birth_date']

    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        form.fields['birth_date'].widget = DatePickerInput()
        return form


class StudentUpdateView(UpdateView):
    model = Student
    success_url = reverse_lazy('lms:student-list')
    fields = ['name', 'birth_date']

    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        form.fields['birth_date'].widget = DatePickerInput()
        return form

apps/lms/templates/lms/student_form.html
{% extends "base.html" %}
{% load bootstrap %}

{% block content %}
    <div class = "row">
    <div class = "col-6">
        {{ form.media }}
        <form method="post">
          {% csrf_token %}
          {{ form|bootstrap }}
          <input type="submit" />
    </form>
    </div>
    </div>
{% endblock %}

apps/lms/templates/lms/student_list.html
{% extends "base.html" %}
{% load lms %}
{% load i18n %}
{% block content %}

    <h1>UPDATED!</h1>
    <h1>UPDATED!</h1>
    <h1>UPDATED!</h1>
    <h1>UPDATED!</h1>
    <h1>UPDATED!</h1>
    <h1>UPDATED!</h1>


<h1>{% trans "Student list" %}</h1>

<ul>
    {% for student in object_list %}
        <li><a href="{% url "lms:student-update" pk=student.id %}">{{ student.name | add_5 }} {{student.birth_date}}</a></li>
    {% endfor %}
    <li><a href="{% url "lms:student-create" %}"> + add </a></li>
    </ul>

{% blocktrans %}
    Hi! thi
    s is<br/>
    a text
    asdas<b>Boold</b> {{request.user}}
{% endblocktrans %}

{% endblock %}