apps/authentication/urls.py
from django.urls import path

from apps.authentication.views import LoginView, AccountView, LogoutView, RegisterView


app_name = 'authentication'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('account/', AccountView.as_view(), name='account'),
    path('register/', RegisterView.as_view(), name='register')
]

apps/lms/urls.py
from django.urls import path

from apps.lms.views import StudentListView, StudentCreateView, StudentUpdateView

app_name = 'lms'


urlpatterns = [
    path('', StudentListView.as_view(), name='student-list'),
    path('student', StudentCreateView.as_view(), name='student-create'),
    path('student/<str:pk>/', StudentUpdateView.as_view(), name='student-update')
]

config/urls.py
from django.contrib import admin
# from django.http import HttpResponse
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns


# def my_view(request):
#     return HttpResponse('OK')


urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('apps.imdb.urls', namespace='imdb')),
    path('lms/', include('apps.lms.urls', namespace='lms')),
    path('admin/', admin.site.urls),
    path('auth/', include('apps.authentication.urls', namespace='auth')),

]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block page_title %} Title {% endblock %}</title>
    <link href="{% static "bootstrap/bootstrap.min.css" %}"
          rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.2.slim.min.js" ></script>

<!--    <script src="{% static "admin/js/jquery.init.js" %}"></script>-->
</head>
    <body>

    {% block header %}
        {% include "navbar.html" %}
    {% endblock %}
    {% block content %}
    {% endblock %}

    <script src="{% static "bootstrap/popper.min.js" %}"
            integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
            crossorigin="anonymous"></script>
    <script src="{% static "bootstrap/bootstrap.min.js" %}"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>


    </body>
</html>

templates/navbar.html
            <!-- Navbar -->
{% load i18n %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <!-- Container wrapper -->
  <div class="container-fluid">
    <!-- Toggle button -->
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Navbar brand -->
      <a class="navbar-brand mt-2 mt-lg-0" href="#">
        <img
          src="https://mdbcdn.b-cdn.net/img/logo/mdb-transaprent-noshadows.webp"
          height="15"
          alt="MDB Logo"
          loading="lazy"
        />
      </a>
      <!-- Left links -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url "auth:account" %}">Account</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url "lms:student-list" %}">List students</a>
        </li>
      </ul>
      <!-- Left links -->
    </div>
    <!-- Collapsible wrapper -->

    <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
      <input name="next" type="hidden" value="{{ redirect_to }}">
      <select name="language">
          {% get_current_language as LANGUAGE_CODE %}
          {% get_available_languages as LANGUAGES %}
          {% get_language_info_list for LANGUAGES as languages %}
          {% for language in languages %}
              <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                  {{ language.name_local }} ({{ language.code }})
              </option>
          {% endfor %}
      </select>
      <input type="submit" value="Go">
    </form>


    {% if request.user.is_authenticated %}
      <div class="dropdown">
        <a class="dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
          {{ request.user }}
        </a>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
          <li><a class="dropdown-item" href="{% url "auth:logout" %}">Log out</a></li>
        </ul>
      </div>
    {% else %}
      <a href="{% url "auth:login" %}">Log in</a>
    {% endif %}

    <!-- Right elements -->
    <div class="d-flex align-items-center">

  <!-- Container wrapper -->
</nav>
<!-- Navbar -->